### ISSUE TITLE
level should be written on the top level

### ISSUE THREAD

**Issue by dollschasingmen** [truerss/rollbar-scala#2]
currently it looks like level is being written on the body level

https://github.com/truerss/rollbar-scala/blob/master/src/main/scala/com/github/truerss/rollbar/entities.scala#L39

it should be on the data level (ie, same level as `body`)

**Comment by fntz** [comment]
seems, i used an old api, i update it, soon

**Comment by dollschasingmen** [comment]
i can make a PR

**Comment by fntz** [comment]
https://github.com/truerss/rollbar-scala/pull/5
