### ISSUE TITLE
ability to notify w/ stacktraces

### ISSUE THREAD

**Issue by dollschasingmen** [truerss/rollbar-scala#3]
Ability to build stacktrace frames as rollbar understands, similar to this:

https://github.com/rollbar/clj-rollbar/blob/master/src/clj_rollbar/core.clj#L123-L131

**Comment by dollschasingmen** [comment]
hmm maybe another approach would be to translate from the java side using something similar to BodyFactory: 

https://github.com/rollbar/rollbar-java/blob/f05e8edc5a82d97ceed5e605a4cae4ddb2167e87/rollbar-java/src/main/java/com/rollbar/notifier/util/BodyFactory.java

**Comment by fntz** [comment]
it's easy, but i need a time for implement, ~ 1-2 week

**Comment by fntz** [comment]
but, wait

**Comment by fntz** [comment]
new version: `0.0.4`

some changes: 

`Result` now is trait: `SuccessResult` and `FailureResult` for response

`NotifyBuilder.trace` method with Throwable as argument

TypeClass for convert `Throwable` to `Trace`: https://github.com/truerss/rollbar-scala/blob/master/src/main/scala/com/github/truerss/rollbar/ToTrace.scala#L10 you might implement own

update scalaj to `2.3.0`

publish for `scala 2.12`

```
import DefaultImplicits._ // or implement own

val builder = NotifyBuilder(token, "environment")

try {
  // ... throw new RuntimeException("boom!")
} catch {
  case ex: Throwable =>
    Sender.send(builder.trace(ex))
}
```
